var app=angular.module("allModule",[]);
app.controller("allctrl",function($scope){
	$scope.numb="All";
	$scope.picss=[
	{src:"image/p1.jpg",tex:"man"},{src:"image/p2.jpg",tex:"backpack"},
	{src:"image/p3.jpg",tex:"man"},{src:"image/p4.jpg",tex:"man"},
	{src:"image/p5.jpg",tex:"man"},{src:"image/p6.jpg",tex:"man"},
	{src:"image/p7.jpg",tex:"man"},{src:"image/p8.jpg",tex:"man"},
	{src:"image/p9.jpg",tex:"man"},{src:"image/p10.jpg",tex:"man"},
	{src:"image/p11.jpg",tex:"man"},{src:"image/p12.jpg",tex:"man"},
	{src:"image/p13.jpg",tex:"man"},{src:"image/p14.jpg",tex:"man"},
	{src:"image/p15.jpg",tex:"man"},{src:"image/i139.jpg",tex:"人"},
	{src:"image/i149.jpg",tex:"main"},{src:"image/i159.jpg",tex:"main"},
	{src:"image/i1111.jpg",tex:"main"},{src:"image/i1210.jpg",tex:"花"},
	{src:"image/i1091.jpg",tex:"main"},{src:"image/i111.jpg",tex:"main"},
	{src:"image/i59.jpg",tex:"房子"},{src:"image/i49.jpg",tex:"人"},
	{src:"image/i39.jpg",tex:"房子"},{src:"image/i29.jpg",tex:"main"},
	{src:"image/i129.jpg",tex:"main"},{src:"image/p1_1.jpg",tex:"man"},
	{src:"image/p1_2.jpg",tex:"backpack"},{src:"image/p1_3.jpg",tex:"man"},
	{src:"image/p1_4.jpg",tex:"man"},{src:"image/p1_5.jpg",tex:"man"},
	{src:"image/p1_6.jpg",tex:"man"},{src:"image/p1_7.jpg",tex:"man"},
	{src:"image/p1_8.jpg",tex:"man"},{src:"image/p1_9.jpg",tex:"man"},
	{src:"image/p1_10.jpg",tex:"man"},{src:"image/p1_11.jpg",tex:"man"},
	{src:"image/p1_12.jpg",tex:"man"},{src:"image/p1_13.jpg",tex:"man"},
	{src:"image/p2_1.jpg",tex:"man"},{src:"image/p2_2.jpg",tex:"backpack"},
	{src:"image/p2_3.jpg",tex:"man"},{src:"image/p2_4.jpg",tex:"man"},
	{src:"image/p2_5.jpg",tex:"man"},{src:"image/p2_6.jpg",tex:"man"},
	{src:"image/p2_7.jpg",tex:"man"},{src:"image/p2_8.jpg",tex:"man"},
	{src:"image/p2_9.jpg",tex:"man"},{src:"image/p2_10.jpg",tex:"man"},
	{src:"image/p2_11.jpg",tex:"man"},{src:"image/p2_12.jpg",tex:"man"},
	{src:"image/p2_13.jpg",tex:"man"},{src:"image/p2_14.jpg",tex:"man"},
	{src:"image/p2_15.jpg",tex:"man"},{src:"image/p2_16.jpg",tex:"man"},
	{src:"image/o1.jpg",tex:"man"},{src:"image/o2.jpg",tex:"backpack"},
	{src:"image/o4.jpg",tex:"man"},{src:"image/o5.jpg",tex:"man"},
	{src:"image/o6.jpg",tex:"man"},{src:"image/o7.jpg",tex:"man"},
	{src:"image/o8.jpg",tex:"man"},{src:"image/o9.jpg",tex:"man"},
	{src:"image/o10.jpg",tex:"man"},{src:"image/o11.jpg",tex:"man"},
	{src:"image/o12.jpg",tex:"man"},{src:"image/o13.jpg",tex:"man"},
	{src:"image/o14.jpg",tex:"man"},{src:"image/o15.jpg",tex:"man"},
	{src:"image/i129.jpg",tex:"main"},{src:"image/p1_1.jpg",tex:"man"},
	{src:"image/p1_2.jpg",tex:"backpack"},{src:"image/p1_3.jpg",tex:"man"},
	{src:"image/p1_4.jpg",tex:"man"},{src:"image/p1_5.jpg",tex:"man"},
	{src:"image/p1_6.jpg",tex:"man"},{src:"image/p1_7.jpg",tex:"man"},
	{src:"image/p1_8.jpg",tex:"man"},{src:"image/p1_9.jpg",tex:"man"},
	{src:"image/p1_10.jpg",tex:"man"},{src:"image/p1_11.jpg",tex:"man"},
	{src:"image/p1_12.jpg",tex:"man"},{src:"image/p1_13.jpg",tex:"man"},
	{src:"image/p2_1.jpg",tex:"man"},{src:"image/p2_2.jpg",tex:"backpack"}];
 //	console.log($scope.picss.length)
	$scope.show=function(scope){
		$scope.n=$scope.picss[this.$index].src;
		$scope.te=$scope.picss[this.$index].tex;
		$scope.current=true;
	    var that=this.$index;
	$scope.rightgo=function(){
		    that++;
	if(that>$scope.picss.length-1){
		that=0;
	    }
	$scope.te=$scope.picss[that].tex;
	$scope.n=$scope.picss[that].src;
	 }
	$scope.leftgo=function(){
		   that--;
	if(that<0){
		that=$scope.picss.length-1
	    }
	$scope.te=$scope.picss[that].tex;
	$scope.n=$scope.picss[that].src;
	 }
	}
	$scope.hide=function(scope){
		$scope.current=false;
	}
})
