var app=angular.module("homeModule",[]);
app.controller("homectrl",function($scope){
	$scope.numb=`home`;
	$scope.tt=['竹田 嘉文',
'82年生。名古屋市出身。東京在住。デザイン事務所でモーシ',
"ョングラフィックデザイナーとして勤務後'10年よりフリー。",
'イラストレーターとしての活動を開始。',
'*Awards & Recognition',
'165回　The　Choice　名久井直子さん選　入選',
'*Book',
'西田征史著「小野寺の弟.小野寺の姉」（リンダパブリッシャ',
'ーズ）　朝倉 かすみ著「そんなはずない」（角川文庫）',
'有沢佳映著「アナザー修学旅行」（講談社）',
'*Magazine',
'SPECTATOR(エディトリアルデパートメント）',　
'OUTSTANDING(講談社)　ku:nel (マガジンハウス)　GOETHE(幻',
'冬舎)　ecocolo (エスプレ)　papyrus (幻冬舎).',
'2nd (エイ出版社)　日経ヘルス(日経BPマーケティング)',
'HUgE(講談社)　popeye(マガジンハウス)　Hanakoformen(マガジンハウス)',
'corner(エスプレ)',
'*Music',
'Mr.children dome tour 2005 「靴ひも」アニメーション',
'（OORONG-SHA）',
'*Web／Mobile',
'webちくま（筑摩書房）',
'*Others',
'アノニマだより（アノニマスタジオ）　セイカノート（精華',
'大学京都）　Savta Gamila(シービック)　and more...',
'TAKEDA YOSHIFUMI',
'Born in Nagoya in 1982, currently based in',
'Tokyo.After working as a motion graphic ',
'designer, became a freelance in 2010 and began' ,
'his career as an illustrator.',
'*Awards & Recognition',
'Selected for the 165th Choice award by Naoko', 
'Nakui',
'*Book',
"Masafumi Nishida's Onoderanoototo",
"Onoderanoane Kasumi Asakura's book",
'School Trip',

'*Magazine',
'SPECTATOR, OUTSTANDING, ku:nel, GOETHE, ',
'ecocolo, papyrus, 2nd, Nikkei Health, HUgE,'　,
'popeye, Hanako for men, corner',
'*Music',
'Mr.children dome tour 2005 ',
'"Shoelace"Animation(OORONG-SHA）',
'*Web／Mobile',
'web CHIKUMA（CHIKUMA SHOBO）',
'*Others',
'anonima letter（anonima studio） Seika',
'Note（KYOTO SEIKA UNIVERSITY） Savta ',
'Gamila(CBIC) and more...'];
})
